### ISSUE TITLE
They changed the wording when it comes to physical damage as extra chaos :'(

### ISSUE THREAD

**Issue by Meisen1977** [veiset/poe-vendor-string#134]
Your site calls this mod: Monsters deal #% extra Physical Damage as Chaos Monsters Inflict Withered for 2 seconds on Hit

But in game, on maps it's called: Monsters gain #% of their physical damage as extra chaos damage.

Super sad since we no longer can filter out all the phys as extra mods with "% e" :'(

![image](https://github.com/veiset/poe-vendor-string/assets/120154273/06eb7196-481f-47fc-b3ee-295859b419cd)

EDIT: I see i didn't write down the wither portion of the mod, but that isn't the part that matters, and you also have the screenshot, so i guess no confusion there is possible :)

**Comment by veiset** [comment]
Hey. Thanks for the report.

I'll try to get some time to work on this during the weekend. I want to automate some stuff better at the backend. 

I'm thinking of taking https://www.poewiki.net/wiki/List_of_map_mods as a base for generating the regexes, as its currently a bit of a manual process. 

I'll keep you updated and hopefully its going to be fixed pretty soon.

**Comment by Moremackles** [comment]
I'm not sure if this is a situation where I should open a new issue or if I should report here since I'm new to github, but I believe the wording on:

>  Monsters have a 20% chance to cause Elemental Ailments on hit

 has also changed to: 

>  Monsters have a 20% chance Ignite, Freeze and Shock on Hit

as seen in game [here](https://imgur.com/a/qKYHCKy) and also on the wiki [here](https://www.poewiki.net/index.php?title=Modifier:MapMonstersChanceToInflictStatusAilments2MapWorlds&diff=prev&oldid=1425636)
