### ISSUE TITLE
Feature: Reverse Regex

### ISSUE THREAD

**Issue by MDLeide** [veiset/poe-vendor-string#171]
I'd love to see a feature where the user inputs a regex and the site highlights all the mods that it picks up. I have a few regex strings saved that I cannot decipher :)

**Comment by veiset** [comment]
This is currently supported, all you have to do is paste your regex in to the modifier search field: 

<img width="627" alt="image" src="https://github.com/user-attachments/assets/51cd228d-0e32-439e-befd-7e66f839c65a">

It doesn't support quant/qual or any of the checkboxes. Let me know if this works for you.

**Comment by MDLeide** [comment]
Oh wild. I kept trying to put it in the output, which in retrospect is a little silly. I guess I was tunnel visioned on that and didn't see the watermark on the textbox (TIP: HERE'S THE THING YOU ARE ABOUT TO OPEN AN ISSUE ABOUT).

Yes, this works great, thanks for the response, and thanks for the site.

Off-topic, but, do you think you could squeeze two more characters in by eliminating the quotes and using periods in place of spaces? That's how I write mine, and I haven't had any problems, but there could be some unforeseen issues. I've been thinking about this for ages.

**Comment by veiset** [comment]
No worries!

Yeah, there are a few issues with using periods instead of spaces and qoutes.

An example:

Text:
```
hey uthere
youtube
```

`"y u"` would only match the first one, while `y.u` would match both.

I am currently attempting to write a solver for a generalized version of this problem, but it might take some time. The idea is that you can have regexes such as `a.+b` but at the moment the algorithm uses around 15 minutes to generate the lookup-table for this. Its insanely slow.
