### ISSUE TITLE
Feature Suggestion: Flasks

### ISSUE THREAD

**Issue by andrewkhunn** [veiset/poe-vendor-string#19]
Alt/aug rolling flasks would be immensely more tolerable with a good regex string generator to target our desired prefix/suffixes. Because the mod pool is relatively small (I'm not even sure that lower tiers would need to be supported, because who rolls for tier: 5 evasion rating?) I can't imagine it would be too difficult to implement.

Thanks for the consideration and the great tool!

**Comment by veiset** [comment]
Nice. This is a very good suggestion, and something I see myself using. I'll implement this before next league start for sure. Probably before.

I will still need to consider all the mods and tiers for generating the regex but it should still be reasonably straight forward. 

Would an option for rolling lower tier flasks be nice to have? Write in the flask ilevel (and default to it if none) and only target the highest tier the flask can roll of selected prefix/suffix?

Is there a use case for things like prefix: "either armour OR evasion" + suffix: "duration OR effect" you think? Or would armour + duration simply be enough?

**Comment by andrewkhunn** [comment]
Yeah max tier for a given ilvl is a good way to reduce complexity while still allowing for lower tier support.

Because suffixes for a given set of flasks are generally interchangeable (i.e. you have 5 max suffixes for a given flask setup that you are targetting in totality), allowing that to be flexible seems prudent.

Example: I was targetting "Flagellant's" prefix and any of "Armadillo", "Dove", "Owl", or "Rainbow" across 4 of my 5 flasks this league. I didn't specifcally need those suffixes to be on any particular flask.

Not sure if supporting life/mana/hybrid flasks is worth the effort. Also, AFAIK Diamond, Iron, and Silver Flasks have slightly different modpools. Just a head's up.

**Comment by veiset** [comment]
The flask mods are a mess to group based on utility/life/mana, I've found no way to do it automatically based on the mod weights. For now I'll list all the possible mods without the possibility of selecting a flask type.

I got a very rough prototype going (it should work, but it needs more testing and polishing).

You can check it out at https://poe.re/#/flasks

**Comment by andrewkhunn** [comment]
This is great!

Would it be possible to optionally match the prefix/suffix independently? Quite often, I will roll until I get either affix and then annul/aug as appropriate.

**Comment by veiset** [comment]
Thanks for the feedback!

https://poe.re/#/flasks is updated with:

* Optionally match prefix/suffix independently
* Choice for highest item level for both prefix and suffix
* Colors to distinguish between the different mod types (the color tag system is very naive and is based on the mod description text)
* Information text about the minimum flask item level based on chosen mods

The flask page is still "hidden", meaning you need the direct link to find it at the moment.

I'm pretty happy about how this turned out. I just need to do some actual testing and then I'll add a link to the page. Let me know if you find any bugs or if you got some suggestions to make the texts/descriptions clearer.

**Comment by veiset** [comment]
Implemented in #21 - Should be live now.

**Comment by andrewkhunn** [comment]
This is excellent. Thanks for developing this feature!

I'll let you know if I think of anything else, or find any bugs/inconsistencies. 👍🏼
