### ISSUE TITLE
Monsters cannot be stunned "stu" overlap

### ISSUE THREAD

**Issue by CharlieBaird** [veiset/poe-vendor-string#20]
When flagging maps to highlight when they roll "monsters cannot be stunned," poe.re uses 'stu' as the handler. However, this was causing problems as I was rolling an eSTUary map, for obvious reasons.

Are the shortened strings meant to handle situations like this? Otherwise, it seems that "stun" instead of "stu" would fix.

**Comment by veiset** [comment]
It should handle these edge cases, but I found the problem causing this. The regexes are currently generated with the maps that are on the atlas, and since Estuary isn't in the current map pool the regex doesn't account for it.

Currently out traveling, but I will fix this when I'm back from vacation.

**Comment by veiset** [comment]
This is fixed with 1070658 and should be live on the webpage. Thanks for the bug report!
