### ISSUE TITLE
Regex for "Area has patches of Consecrated Ground" is longer than needed?

### ISSUE THREAD

**Issue by Meisen1977** [veiset/poe-vendor-string#50]
This currently gets shortened to "!nsecrate" when, if my eyes do not deceive me, "!f co" would do?

**Comment by veiset** [comment]
Hey, thanks for reporting this!

It looks like you can shorten it at first glance, but I did a check for the regex generator. The issue is that `f co` will match affixes of magic maps. It will match the following things:

```
area has patches of consecrated ground
of Congealment	Cannot Leech from Monsters		
of Consecration	Area has patches of Consecrated Ground
```

So the issue here is really that it will match magic maps with the affix `Cannot Leech from Monsters`, since a Dunes map with that modifier will be named `Dune Map of Congealment`, and then be matched `f co`. 

Appreciate the report nonetheless! :D

**Comment by Meisen1977** [comment]
I see... Thanx for the reply kind sir :)

I must say, for me personally, as i never run magic maps, i'd prefer to go with the "f co" version to save those 4 chars in the regex, but i very much understand that you need to make something that is "foolproof" and catches every, or at least close to every use case :)
