### ISSUE TITLE
Flask Suffix T1 Bleeding Immunity Assuaging from 'ass' to 'assu'

### ISSUE THREAD

**Issue by hgcourtney** [veiset/poe-vendor-string#59]
The current Affix for Flask bleed immunity is "ass" for Assuaging. This is too ambiguous.  Needs to be changed to "assu"

Flask Suffix 
Grants Immunity to Bleeding for (15-17) seconds if used while Bleeding Grants Immunity to Corrupted Blood for (15-17) seconds if used while affected by Corrupted Blood

Name	of Assuaging
https://www.poewiki.net/wiki/Modifier:FlaskBleedCorruptingBloodImmunity4~

Current 
"ass"
![image](https://user-images.githubusercontent.com/44713413/232895578-09450a20-2f04-4dd8-be54-1dd227fe647c.png)

New should be
"assu"
![image](https://user-images.githubusercontent.com/44713413/232896015-6cd79795-a789-4939-bada-1dfcd4de06b5.png)
![image](https://user-images.githubusercontent.com/44713413/232896054-cd1ec6d5-cddb-4b07-8bae-e0e7f618e272.png)

**Comment by veiset** [comment]
Thanks for this very well written report! I will take a look at this, and do a bit of work ensuring flask rolling is better. 

All the regexes are generated, so there is something wrong with my base data. I'll look deeper in to what's the issue and try to fix it at its core. My best guess is that its using some old modifier data from before the flask rework some leagues ago.

**Comment by veiset** [comment]
This should be fixed now. I've reworked the flask regex generation flow, so it should be much easier to update mods if changes happens to flasks in the future.

The issue here was that items have a `Item class` in the raw string describing them, and `ass` matched that. A flask (if you copy it) looks something like:

```
Item Class: Life Flasks
Rarity: Magic
Transgressor's Divine Life Flask of Quashing
--------
Recovers 2400 Life over 3.50 Seconds
Consumes 15 of 45 Charges on use
Currently has 0 Charges
--------
Requirements:
Level: 60
--------
```

`Item Class` has been added to tokens when generating the base regex. This should be fixed and be live now, thanks for the report.
