### ISSUE TITLE
Show what regex does when it's from other person

### ISSUE THREAD

**Issue by kruszkush** [veiset/poe-vendor-string#65]
While trading maps on TFT you often get regex from other people, sometimes price of map is different depending what kind of regex is being used (regex for high quantity maps is more expensive). It could be useful to be able to paste regex on website and have it automatically select what's in that regex, thus translating regex code into english language.

**Comment by veiset** [comment]
Hey, I've thought about trying to fix this somehow earlier, but this is pretty hard to solve. Reverse lookup of the regex is kinda tricky (especially for vendor items since some shortening is being done). It is possible, but also quite some work. 

I would love to be able to make something like a sharable url though, e.g `poe.re/#/maps/<HASH>` so you could link to a selection.

**Comment by veiset** [comment]
Partially solved by this one:

https://github.com/veiset/poe-vendor-string/issues/110

**Comment by kruszkush** [comment]
<3

czw., 4 sty 2024 o 00:53 Vegard Veiset ***@***.***>
napisał(a):
